openapi: 3.0.3
info:
  title: Workflow API
  version: 0.1.0
servers:
  - url: http://localhost:8130
paths:
  /health:
    get:
      summary: Health check
      responses:
        '200':
          description: OK

