[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "cortx-rulepack-sdk"
version = "0.1.0"
description = "SDK for building CORTX RulePack validation containers"
authors = [{name = "Sinergy Solutions"}]
requires-python = ">=3.11"
dependencies = [
  "pydantic>=2.8",
  "httpx>=0.27.0",
  "typing-extensions>=4.9.0",
  "cortx-core>=0.1.0"
]

[project.optional-dependencies]
dev = [
  "pytest>=7.4.0",
  "pytest-asyncio>=0.21.0",
  "pytest-mock>=3.11.0",
  "black>=23.0.0",
  "ruff>=0.1.0",
  "mypy>=1.5.0"
]

[tool.setuptools.packages.find]
where = ["."]
include = ["cortx_rulepack_sdk*"]

[tool.mypy]
python_version = "3.11"
strict = true
warn_unused_ignores = true

[tool.ruff]
line-length = 100
select = ["E", "F", "I", "UP", "B", "SIM", "PL"]

[tool.black]
line-length = 100
