[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "cortx-core"
version = "0.1.0"
description = "CORTX core models, logging, auditing, security, and DB access"
requires-python = ">=3.11"
dependencies = [
  "fastapi>=0.115.0",
  "pydantic>=2.8",
  "pydantic-settings>=2.3",
  "uvicorn>=0.30",
  "structlog>=24.1",
  "sqlalchemy>=2.0",
  "asyncpg>=0.29",
  "python-dotenv>=1.0",
  "httpx>=0.27"
]

[tool.ruff]
line-length = 100
