name: Test Workflow Service

on:
  push:
    branches: [main]
    paths:
    - services/workflow/**
    - .github/workflows/test-workflow.yml
  pull_request:
    branches: [main]
    paths:
    - services/workflow/**
    - .github/workflows/test-workflow.yml

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services/workflow

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: pip
        cache-dependency-path: |
          services/workflow/requirements.txt
          services/workflow/requirements-dev.txt

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi

    - name: Run linting with ruff
      run: |
        ruff check app/ tests/ --config pyproject.toml || true

    - name: Run formatting check with black
      run: |
        black --check app/ tests/ || true
      continue-on-error: true

    - name: Run type checking with mypy
      run: |
        mypy app/ --config-file pyproject.toml || true
      continue-on-error: true

    - name: Run tests with pytest
      run: |
        pytest tests/ \
          --cov=app \
          --cov-report=term-missing \
          --cov-report=xml \
          --cov-report=html \
          --cov-fail-under=80 \
          -v

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./services/workflow/coverage.xml
        flags: workflow
        name: workflow-coverage
        fail_ci_if_error: false

    - name: Upload coverage artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: workflow-coverage
        path: |
          services/workflow/coverage.xml
          services/workflow/htmlcov/
        retention-days: 30

    - name: Check coverage threshold
      run: |
        coverage report --fail-under=80
